include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**.vibe.dart"

custom_Lint:
  debug: true
  verbose: true

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas
    - prefer_relative_imports
