name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vibe:
    path: ../vibe

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  vibe_lint:
    path: ../vibe_lint

flutter:
  uses-material-design: true
