name: vibe_lint
description: A linter for [vibe] framework.
version: 0.1.4
repository: https://github.com/hypen-flutter/vibe.git

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  analyzer: ^6.4.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.4
  # path: ^1.8.0

dev_dependencies:
  custom_lint: ^0.6.4
  lints: ^3.0.0
  test: ^1.24.0
