name: vibe_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.4
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

executables:
  vibe: vibe_cli

# Add regular dependencies here.
dependencies:
  analyzer: ^6.5.0
  ansicolor: ^2.0.2
  args: ^2.5.0
  async: ^2.11.0
  cli_completion: ^0.5.0
  dart_style: ^2.3.6
  meta: ^1.15.0
  path: ^1.9.0
  rxdart: ^0.28.0
  source_gen: ^1.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
