name: vibe_cli
description: A cli tool to build [vibe] framework.
version: 0.0.6
repository: https://github.com/hypen-flutter/vibe/

environment:
  sdk: ^3.4.4

executables:
  vibe: vibe_cli

# Add regular dependencies here.
dependencies:
  analyzer: ^6.5.0
  ansicolor: ^2.0.2
  args: ^2.5.0
  async: ^2.11.0
  cli_completion: ^0.5.0
  dart_style: ^2.3.6
  meta: ^1.12.0
  path: ^1.9.0
  recase: ^4.1.0
  rxdart: ^0.28.0
  source_gen: ^1.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
